doc: Mention hashing the public keys
LoupVaillant/Monocypher pull request #232
Opened 2022-02-12 20:44 UTC by samuel-lucas6

Closes #230. May need some rewording.

2022-02-12 20:51 UTC, fscoto requested changes
Should we also mark the function as deprecated and likely to be removed in a future release considering it's just... not good?

2022-02-12 20:51 UTC, fscoto commented on doc/man/man3/crypto_key_exchange.3monocypher
> +shared secret concatenated with both public keys. For example,
troff is sensitive to periods.

```
This is a sentence.
This is another sentence.
```

[will use sentence spacing](https://mandoc.bsd.lv/mdoc/intro/punctuation.html), but

```
This is a sentence. This is another sentence.
```

will not.

Please add newlines after each period.

2022-02-12 20:51 UTC, fscoto commented on doc/man/man3/crypto_key_exchange.3monocypher
> +.\" Richard Walmsley and Samuel Lucas
Please update `.Dd` on line 56, too, since the manual contents changed.

2022-02-12 20:51 UTC, fscoto commented on doc/man/man3/crypto_key_exchange.3monocypher
> +.Fn BLAKE2b(shared_secret || your_pk || their_pk)
[`.Fn`](https://man.openbsd.org/mdoc.7#Fn) is used only for function names. `BLAKE2b()` is not a function.

Instead use [`.Dl`](https://man.openbsd.org/mdoc.7#Dl) (indented) or [`.Ql`](https://man.openbsd.org/mdoc.7#Ql).

2022-02-12 21:08 UTC, samuel-lucas6 commented
Sorry, not used this before. Thanks @fscoto :)

2022-02-12 22:29 UTC, merged

2022-02-14 14:07 UTC, samuel-lucas6 commented
This unfortunately doesn't seem to be formatted properly on the website:

![temp](https://user-images.githubusercontent.com/63159663/153879209-233d2a57-a84a-4928-8427-010b9ecbee7b.PNG)

2022-02-14 20:06 UTC, LoupVaillant commented
@samuel-lucas6 good catch, thanks. Both issues should be fixed now.

2022-02-15 09:38 UTC, samuel-lucas6 commented
> @samuel-lucas6 good catch, thanks. Both issues should be fixed now.

I'm afraid the 'Security Considerations' fix doesn't seem to have worked. I've also noticed the ChaCha20, IETF ChaCha20, and HChaCha20 pages in 'Advanced' and 'Deprecated' haven't got the second 'c' capitalised, which was changed in the text of these pages.

2022-02-15 19:27 UTC, LoupVaillant commented
> I'm afraid the 'Security Considerations' fix doesn't seem to have worked.

Refresh with Ctrl+F5, or hold the control key when clicking on the "refresh" button. I have noticed that you often need such deep refreshes to make the fix visible (it’s a CSS fix, not an HTML one).

> I've also noticed the ChaCha20, IETF ChaCha20, and HChaCha20 pages in 'Advanced' and 'Deprecated' haven't got the second 'c' capitalised

Oops, I forgot to update the side bar… Fixed now.

2022-02-15 20:30 UTC, samuel-lucas6 commented
> Refresh with Ctrl+F5, or hold the control key when clicking on the "refresh" button. I have noticed that you often need such deep refreshes to make the fix visible (it’s a CSS fix, not an HTML one).

Tried that on three browsers, and it sadly didn't work.

One more thing (sorry) is that the 'Home' page link to 'Public Key Cryptography' no longer works.

2022-02-15 23:25 UTC, LoupVaillant commented
> the 'Home' page link to 'Public Key Cryptography' no longer works.

Oh, yes, shuffling the pages around broke the link. Correcting now, thanks.

> Tried that on three browsers, and it sadly didn't work.

OK, now I'm very, *very* surprised. Here's what I'm seeing right now:

![Screenshot from 2022-02-16 00-13-44](https://user-images.githubusercontent.com/27145845/154165956-9f5a00cc-a3e6-4f7a-8c64-73fc1c5bdb3b.png)

Aren't seeing this result? If not, can you take a look at https://monocypher.org/css/style.css and confirm the presence of the following code?

```CSS
div.Bd {
    margin: -1.5rem 0 0 1.5rem;
}
```

Quite hack-ish, but I think that's what most closely imitates the layout on the man page itself (newline, indent, no vertical spacing). I could change the font to fixed size, but hesitated to do so because this is not valid C code.

2022-02-16 09:45 UTC, samuel-lucas6 commented
> Aren't seeing this result? If not, can you take a look at https://monocypher.org/css/style.css and confirm the presence of the following code?

Ok that is what I'm seeing, and the CSS is present. I was expecting the last bit to be on one line.